# Generated by Django 3.0.3 on 2020-02-22 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserequest',
            name='create_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baserequest',
            name='start_dttm',
            field=models.DateTimeField(null=True),
        ),
    ]
