# Generated by Django 3.0.3 on 2020-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_common', '0002_auto_20200222_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserequest',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
