# Generated by Django 3.0.3 on 2020-02-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_common', '0003_baserequest_is_initialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='duration_sec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='modification_dttm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='start_sec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='order_n',
            field=models.IntegerField(null=True),
        ),
    ]
