# Generated by Django 3.0.3 on 2020-02-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dttm', models.DateTimeField()),
                ('finish_dttm', models.DateTimeField(null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_finish_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExportProto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto_nm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFileRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_nm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TranscodeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_nm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline_panel.BaseRequest')),
                ('sdroot_path_txt', models.CharField(max_length=200)),
            ],
            bases=('pipeline_panel.baserequest',),
        ),
        migrations.CreateModel(
            name='ExportDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_nm', models.CharField(max_length=50)),
                ('destination_params_txt', models.CharField(max_length=200)),
                ('export_proto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline_panel.ExportProto')),
            ],
        ),
        migrations.CreateModel(
            name='TranscodeRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline_panel.BaseRequest')),
                ('import_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline_panel.ImportRequest')),
                ('transcode_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline_panel.TranscodeProfile')),
            ],
            bases=('pipeline_panel.baserequest',),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_txt', models.CharField(max_length=200)),
                ('order_n', models.IntegerField()),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline_panel.MediaFileRole')),
                ('transcode_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline_panel.TranscodeRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline_panel.BaseRequest')),
                ('export_params_txt', models.CharField(max_length=200)),
                ('progress_prc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('export_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline_panel.ExportDestination')),
                ('media_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline_panel.MediaFile')),
            ],
            bases=('pipeline_panel.baserequest',),
        ),
    ]
